- name: Debian and docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_version }} main
    update_cache: yes
    state: present
  tags: [docker]

- name: Installing Docker Engine
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]
   
